--- #YAML:1.0
name:                IO-Compress-Bzip2
version:             2.006
abstract:            Write bzip2 files/buffers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Compress::Raw::Bzip2:          2.006
    IO::Compress::Base:            2.006
    IO::Uncompress::Base:          2.006
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Paul Marquess <pmqs@cpan.org>
